[package]
name = "xstream-util"
version = "1.0.0"
authors = ["Erik Brinkman <erik.brinkman@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/erikbrinkman/xstream"
repository = "https://github.com/erikbrinkman/xstream"
license = "MIT"
description = "A command line tool to split a stream to child processes"
edition = "2018"

[badges]
travis-ci = { repository = "erikbrinkman/xstream" }

[[bin]]
name = "xstream"
path = "src/main.rs"

[dependencies]
clap = "^2.33"
